version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch624
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/local/var/lib/elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    links:
      - 'elasticsearch'

volumes:
  esdata1:
    driver: local